version: "3"
services:
  # Nginx Service
  webserver:
    image: nginx:alpine
    build:
      context: nginx
      dockerfile: Dockerfile-nginx
    hostname: webserver
    environment:
      DEV_COMMENT: "#" # Disable prod settings
      PROD_COMMENT: "" # Enable dev settings
      HEALTH_ISSUER_SSL_DOMAIN_PATH: ${HEALTH_ISSUER_SSL_DOMAIN_PATH}
      HEALTH_ISSUER_SERVER_NAME: ${HEALTH_ISSUER_SERVER_NAME}
      HEALTH_ISSUER_HTTPS_PORT: ${HEALTH_ISSUER_HTTPS_PORT}
      HEALTH_ISSUER_HTTP_PORT: ${HEALTH_ISSUER_HTTP_PORT}
      PRIMARY_VERIFIER_SSL_DOMAIN_PATH: ${PRIMARY_VERIFIER_SSL_DOMAIN_PATH}
      PRIMARY_VERIFIER_SERVER_NAME: ${PRIMARY_VERIFIER_SERVER_NAME}
      PRIMARY_VERIFIER_HTTPS_PORT: ${PRIMARY_VERIFIER_HTTPS_PORT}
      PRIMARY_VERIFIER_HTTP_PORT: ${PRIMARY_VERIFIER_HTTP_PORT}
      SECONDARY_VERIFIER_SSL_DOMAIN_PATH: ${SECONDARY_VERIFIER_SSL_DOMAIN_PATH}
      SECONDARY_VERIFIER_SERVER_NAME: ${SECONDARY_VERIFIER_SERVER_NAME}
      SECONDARY_VERIFIER_HTTPS_PORT: ${SECONDARY_VERIFIER_HTTPS_PORT}
      SECONDARY_VERIFIER_HTTP_PORT: ${SECONDARY_VERIFIER_HTTP_PORT}
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "4443:4443"
      - "8080:8080"
      - "4444:4444"
    volumes:
      - ./health-issuer-ui/build:/var/www/health-issuer-ui:consistent
      - ./primary-verifier-ui/build:/var/www/primary-verifier-ui:consistent
      - ./secondary-verifier-ui/build:/var/www/secondary-verifier-ui:consistent
      - ./nginx/ssl:/etc/nginx/ssl:consistent
      - ./health-issuer-api:/var/www/health-issuer-api:consistent
      - ./primary-verifier-api:/var/www/primary-verifier-api:consistent
      - ./secondary-verifier-api:/var/www/secondary-verifier-api:consistent
      - ./nginx/conf.d/:/etc/nginx/templates/
      - ./nginx/docker-entrypoint.d/create-self-signed.sh:/docker-entrypoint.d/10-create-self-signed.sh
    depends_on:
      - "health-issuer-api"
      - "health-issuer-ui"
      - "primary-verifier-api"
      - "primary-verifier-ui"
      - "secondary-verifier-api"
      - "secondary-verifier-ui"
    networks:
      - app-network

  # DB Service
  db:
    image: postgres:9.5
    hostname: db
    restart: unless-stopped
    #    ports: # Uncomment to access postgres outside of containers
    #      - "5432:5432"
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    networks:
      - app-network

  #***************************************************************
  # Lab Services
  #***************************************************************

  health-issuer-api:
    image: node:12-stretch
    hostname: health-issuer-api
    restart: unless-stopped
    user: root # we want to run with write permissions for dev, so run as root.
    working_dir: /home/node/app
    environment:
      - DB_HOST=${HEALTH_ISSUER_API_DB_HOST}
      - DB=${HEALTH_ISSUER_API_DB}
      - DB_USERNAME=${HEALTH_ISSUER_API_DB_USERNAME}
      - DB_PASSWORD=${HEALTH_ISSUER_API_DB_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - CONTROLLERPORT=3100
      - AGENTADDRESS=http://health-issuer-agent:8150
      - WEB_ROOT=${HEALTH_ISSUER_WEB_ROOT}
      - DISABLE_SSL_CHECK=${DISABLE_SSL_CHECK}
      - JWT_SECRET=${HEALTH_ISSUER_JWT_SECRET}
      - SESSION_SECRET=${HEALTH_ISSUER_SESSION_SECRET}
      - GOVERNANCE_PATH=${GOVERNANCE_PATH}
      - ENC_KEY=${HEALTH_ISSUER_ENC_KEY}
      - SCHEMA_LAB_ORDER=${SCHEMA_LAB_ORDER}
      - SCHEMA_LAB_RESULT=${SCHEMA_LAB_RESULT}
      - SCHEMA_VACCINATION=${SCHEMA_VACCINATION}
      - SCHEMA_VACCINE_EXEMPTION=${SCHEMA_VACCINE_EXEMPTION}
      - SCHEMA_MEDICAL_RELEASE=${SCHEMA_MEDICAL_RELEASE}
    volumes:
      - ./health-issuer-api:/home/node/app:consistent
      - ./wait-for-it:/home/node/wait-for-it
    expose:
      - "3100"
    command: >
      sh -c "npm install && /home/node/wait-for-it/wait-for-it.sh -t 300 ${HEALTH_ISSUER_API_DB_HOST}:5432 && npm run migrate_up_all && npm run dev"
    networks:
      - app-network
    depends_on:
      - "db"

  health-issuer-ui:
    image: node:12-stretch
    hostname: health-issuer-ui
    restart: unless-stopped
    user: root # To write to ui folder, we need write permissions. node user does not have this.
    tty: true # keep react from stopping development server
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - BROWSER=none # don't open the web browser
    volumes:
      - ./health-issuer-ui:/home/node/app:rw
    expose:
      - "3000"
    command: >
      sh -c "npm install && npm start"
    networks:
      - app-network
    depends_on:
      - "db"

  health-issuer-agent:
    build:
      context: .
    environment:
      ACAPY_WEBHOOK_URL: http://health-issuer-api:3100/api/controller-webhook
      ACAPY_ENDPOINT: http://health-issuer-agent:3005
    entrypoint: >
      sh -c '/home/indy/wait-for-it/wait-for-it.sh -t 300 ${HEALTH_ISSUER_AGENT_DB_HOST}:5432 && aca-py "$$@"' --
    volumes:
      - ./wait-for-it:/home/indy/wait-for-it
    command: >
      start -it http 0.0.0.0 3005
      -ot http
      --admin 0.0.0.0 8150 --admin-insecure-mode
      --label 'Health Issuer'
      --plugin acapy_plugin_data_transfer
      --plugin acapy_plugin_qa
      --enable-undelivered-queue
      --wallet-type askar
      --wallet-name ${HEALTH_ISSUER_AGENT_DB}
      --wallet-key default
      --wallet-storage-type postgres_storage
      --wallet-storage-config '{"url":"${HEALTH_ISSUER_AGENT_DB_HOST}:5432"}'
      --wallet-storage-creds '{"account":"${HEALTH_ISSUER_AGENT_DB_USERNAME}","password":"${HEALTH_ISSUER_AGENT_DB_PASSWORD}","admin_account":"${HEALTH_ISSUER_AGENT_ADMIN_DB_USERNAME}","admin_password":"${HEALTH_ISSUER_AGENT_ADMIN_DB_PASSWORD}"}'
      --auto-provision
      --auto-accept-requests
      --auto-ping-connection
      --auto-respond-credential-proposal
      --auto-respond-credential-offer
      --auto-respond-credential-request
      --auto-store-credential
      --auto-respond-presentation-proposal
      --auto-respond-presentation-request
      --auto-verify-presentation
      --debug-connections
      --debug-credentials
      --debug-presentations
      --public-invites
      --invite --invite-label "HEALTH ISSUER (admin)"
      --genesis-url ${GENESIS_URL} 
      ${HEALTH_ISSUER_SEED}
    ports:
      - "3005:3005"
      - "8150:8150"
    networks:
      - app-network
    depends_on:
      - "db"

  health-issuer-proxy:
    image: ghcr.io/indicio-tech/proxy-mediator:0.1.1
    environment:
      PORT: 3000
      ENDPOINT: http://health-issuer-proxy:3000
      ENABLE_STORE: "true"
      REPO_URI: "${HEALTH_ISSUER_PROXY_DB}"
      REPO_KEY: insecure
      LOG_LEVEL: WARNING
    networks:
      - app-network
    depends_on:
      - "db"

  health-issuer-proxy-setup:
    image: ghcr.io/indicio-tech/proxy-mediator-setup:0.1.1
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=health-issuer-proxy:3000,health-issuer-agent:3005
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=10
      - PROXY=http://health-issuer-proxy:3000
      - AGENT=http://health-issuer-agent:8150
      - MEDIATOR_INVITE=https://public.mediator.indiciotech.io?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiMDVlYzM5NDItYTEyOS00YWE3LWEzZDQtYTJmNDgwYzNjZThhIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL3B1YmxpYy5tZWRpYXRvci5pbmRpY2lvdGVjaC5pbyIsICJyZWNpcGllbnRLZXlzIjogWyJDc2dIQVpxSktuWlRmc3h0MmRIR3JjN3U2M3ljeFlEZ25RdEZMeFhpeDIzYiJdLCAibGFiZWwiOiAiSW5kaWNpbyBQdWJsaWMgTWVkaWF0b3IifQ==
    depends_on:
      - health-issuer-proxy
      - health-issuer-agent
    networks:
      - app-network

  #***************************************************************
  # Government Services
  #***************************************************************

  primary-verifier-api:
    image: node:12-stretch
    hostname: primary-verifier-api
    restart: unless-stopped
    user: root # we want to run with write permissions for dev, so run as root.
    working_dir: /home/node/app
    environment:
      - DB_HOST=${PRIMARY_VERIFIER_API_DB_HOST}
      - DB=${PRIMARY_VERIFIER_API_DB}
      - DB_USERNAME=${PRIMARY_VERIFIER_API_DB_USERNAME}
      - DB_PASSWORD=${PRIMARY_VERIFIER_API_DB_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - CONTROLLERPORT=3100
      - AGENTADDRESS=http://primary-verifier-agent:8151
      - WEB_ROOT=${PRIMARY_VERIFIER_WEB_ROOT}
      - DISABLE_SSL_CHECK=${DISABLE_SSL_CHECK}
      - JWT_SECRET=${PRIMARY_VERIFIER_JWT_SECRET}
      - SESSION_SECRET=${PRIMARY_VERIFIER_SESSION_SECRET}
      - GOVERNANCE_PATH=${GOVERNANCE_PATH}
      - ENC_KEY=${PRIMARY_VERIFIER_ENC_KEY}
      - SCHEMA_LAB_ORDER=${SCHEMA_LAB_ORDER}
      - SCHEMA_LAB_RESULT=${SCHEMA_LAB_RESULT}
      - SCHEMA_VACCINATION=${SCHEMA_VACCINATION}
      - SCHEMA_VACCINE_EXEMPTION=${SCHEMA_VACCINE_EXEMPTION}
      - SCHEMA_MEDICAL_RELEASE=${SCHEMA_MEDICAL_RELEASE}
      - SCHEMA_TRUSTED_TRAVELER=${SCHEMA_TRUSTED_TRAVELER}
      - PRIMARY_VERIFIER_API=${PRIMARY_VERIFIER_API}
      - APIKEY=${PRIMARY_VERIFIER_APIKEY}
    volumes:
      - ./primary-verifier-api:/home/node/app:consistent
      - ./wait-for-it:/home/node/wait-for-it
    expose:
      - "3100"
    command: >
      sh -c "npm install && /home/node/wait-for-it/wait-for-it.sh -t 300 ${PRIMARY_VERIFIER_API_DB_HOST}:5432 && npm run migrate_up_all && npm run dev"
    networks:
      - app-network
    depends_on:
      - "db"

  primary-verifier-ui:
    image: node:12-stretch
    hostname: primary-verifier-ui
    restart: unless-stopped
    user: root # To write to ui folder, we need write permissions. node user does not have this.
    tty: true # keep react from stopping development server
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - BROWSER=none # don't open the web browser
    volumes:
      - ./primary-verifier-ui:/home/node/app:rw
    expose:
      - "3000"
    command: >
      sh -c "npm install && npm start"
    networks:
      - app-network
    depends_on:
      - "db"

  primary-verifier-agent:
    build:
      context: .
    environment:
      ACAPY_WEBHOOK_URL: http://primary-verifier-api:3100/api/controller-webhook
      ACAPY_ENDPOINT: http://primary-verifier-agent:3006
    entrypoint: >
      sh -c '/home/indy/wait-for-it/wait-for-it.sh -t 300 ${PRIMARY_VERIFIER_AGENT_DB_HOST}:5432 && aca-py "$$@"' --
    volumes:
      - ./wait-for-it:/home/indy/wait-for-it
    command: >
      start -it http 0.0.0.0 3006
      -ot http
      --admin 0.0.0.0 8151 --admin-insecure-mode
      --label 'Primary Verifier'
      --plugin acapy_plugin_data_transfer
      --plugin acapy_plugin_qa
      --enable-undelivered-queue
      --wallet-type askar
      --wallet-name ${PRIMARY_VERIFIER_AGENT_DB}
      --wallet-key default
      --wallet-storage-type postgres_storage
      --wallet-storage-config '{"url":"${PRIMARY_VERIFIER_AGENT_DB_HOST}:5432"}'
      --wallet-storage-creds '{"account":"${PRIMARY_VERIFIER_AGENT_DB_USERNAME}","password":"${PRIMARY_VERIFIER_AGENT_DB_PASSWORD}","admin_account":"${PRIMARY_VERIFIER_AGENT_ADMIN_DB_USERNAME}","admin_password":"${PRIMARY_VERIFIER_AGENT_ADMIN_DB_PASSWORD}"}'
      --auto-provision
      --auto-accept-requests
      --auto-ping-connection
      --auto-respond-credential-proposal
      --auto-respond-credential-offer
      --auto-respond-credential-request
      --auto-store-credential
      --auto-respond-presentation-proposal
      --auto-respond-presentation-request
      --auto-verify-presentation
      --debug-connections
      --debug-credentials
      --debug-presentations
      --public-invites
      --invite --invite-label "PRIMARY VERIFIER (admin)"
      --genesis-url ${GENESIS_URL}
      ${PRIMARY_VERIFIER_SEED}
    ports:
      - "3006:3006"
      - "8151:8151"
    networks:
      - app-network

  primary-verifier-proxy:
    image: ghcr.io/indicio-tech/proxy-mediator:0.1.1
    environment:
      PORT: 3000
      ENDPOINT: http://primary-verifier-proxy:3000
      ENABLE_STORE: "true"
      REPO_URI: "${PRIMARY_VERIFIER_PROXY_DB}"
      REPO_KEY: insecure
      LOG_LEVEL: WARNING
    networks:
      - app-network

  primary-verifier-proxy-setup:
    image: ghcr.io/indicio-tech/proxy-mediator-setup:0.1.1
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=primary-verifier-proxy:3000,primary-verifier-agent:3006
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=10
      - PROXY=http://primary-verifier-proxy:3000
      - AGENT=http://primary-verifier-agent:8151
      - MEDIATOR_INVITE=https://public.mediator.indiciotech.io?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiMDVlYzM5NDItYTEyOS00YWE3LWEzZDQtYTJmNDgwYzNjZThhIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL3B1YmxpYy5tZWRpYXRvci5pbmRpY2lvdGVjaC5pbyIsICJyZWNpcGllbnRLZXlzIjogWyJDc2dIQVpxSktuWlRmc3h0MmRIR3JjN3U2M3ljeFlEZ25RdEZMeFhpeDIzYiJdLCAibGFiZWwiOiAiSW5kaWNpbyBQdWJsaWMgTWVkaWF0b3IifQ==
    depends_on:
      - primary-verifier-proxy
      - primary-verifier-agent
    networks:
      - app-network

  #***************************************************************
  # Verifier Services
  #***************************************************************

  secondary-verifier-api:
    image: node:12-stretch
    hostname: secondary-verifier-api
    restart: unless-stopped
    user: root # we want to run with write permissions for dev, so run as root.
    working_dir: /home/node/app
    environment:
      - DB_HOST=${SECONDARY_VERIFIER_API_DB_HOST}
      - DB=${SECONDARY_VERIFIER_API_DB}
      - DB_USERNAME=${SECONDARY_VERIFIER_API_DB_USERNAME}
      - DB_PASSWORD=${SECONDARY_VERIFIER_API_DB_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - CONTROLLERPORT=3100
      - AGENTADDRESS=http://secondary-verifier-agent:8154
      - GOVERNANCE_PATH=${GOVERNANCE_PATH}
      - ENC_KEY=${SECONDARY_VERIFIER_ENC_KEY}
      - WEB_ROOT=${SECONDARY_VERIFIER_WEB_ROOT}
      - DISABLE_SSL_CHECK=${DISABLE_SSL_CHECK}
      - JWT_SECRET=${SECONDARY_VERIFIER_JWT_SECRET}
      - SESSION_SECRET=${SECONDARY_VERIFIER_SESSION_SECRET}
      - SCHEMA_TRUSTED_TRAVELER=${SCHEMA_TRUSTED_TRAVELER}
    volumes:
      - ./secondary-verifier-api:/home/node/app:consistent
      - ./wait-for-it:/home/node/wait-for-it
    expose:
      - "3100"
    command: >
      sh -c "npm install && /home/node/wait-for-it/wait-for-it.sh -t 300 ${SECONDARY_VERIFIER_API_DB_HOST}:5432 && npm run migrate_up_all && npm run dev"
    networks:
      - app-network
    depends_on:
      - "db"

  secondary-verifier-ui:
    image: node:12-stretch
    hostname: secondary-verifier-ui
    restart: unless-stopped
    user: root # To write to ui folder, we need write permissions. node user does not have this.
    tty: true # keep react from stopping development server
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - BROWSER=none # don't open the web browser
    volumes:
      - ./secondary-verifier-ui:/home/node/app:rw
    expose:
      - "3000"
    command: >
      sh -c "npm install && npm start"
    networks:
      - app-network
    depends_on:
      - "db"

  secondary-verifier-agent:
    build:
      context: .
    environment:
      ACAPY_WEBHOOK_URL: http://secondary-verifier-api:3100/api/controller-webhook
      ACAPY_ENDPOINT: http://secondary-verifier-agent:3009
    entrypoint: >
      sh -c '/home/indy/wait-for-it/wait-for-it.sh -t 300 ${SECONDARY_VERIFIER_AGENT_DB_HOST}:5432 && aca-py "$$@"' --
    volumes:
      - ./wait-for-it:/home/indy/wait-for-it
    command: >
      start -it http 0.0.0.0 3009
      -ot http
      --admin 0.0.0.0 8154 --admin-insecure-mode
      --label 'Secondary Verifier'
      --plugin acapy_plugin_qa
      --enable-undelivered-queue
      --wallet-type askar
      --wallet-name ${SECONDARY_VERIFIER_AGENT_DB}
      --wallet-key default
      --wallet-storage-type postgres_storage
      --wallet-storage-config '{"url":"${SECONDARY_VERIFIER_AGENT_DB_HOST}:5432"}'
      --wallet-storage-creds '{"account":"${SECONDARY_VERIFIER_AGENT_DB_USERNAME}","password":"${SECONDARY_VERIFIER_AGENT_DB_PASSWORD}","admin_account":"${SECONDARY_VERIFIER_AGENT_ADMIN_DB_USERNAME}","admin_password":"${SECONDARY_VERIFIER_AGENT_ADMIN_DB_PASSWORD}"}'
      --auto-provision
      --auto-accept-requests
      --auto-ping-connection
      --auto-respond-credential-proposal
      --auto-respond-credential-offer
      --auto-respond-credential-request
      --auto-store-credential
      --auto-respond-presentation-proposal
      --auto-respond-presentation-request
      --auto-verify-presentation
      --debug-connections
      --debug-credentials
      --debug-presentations
      --public-invites
      --invite --invite-label "SECONDARY VERIFIER (admin)"
      --genesis-url ${GENESIS_URL} 
      ${SECONDARY_VERIFIER_SEED}
    ports:
      - 3009:3009
      - 8154:8154
    networks:
      - app-network

  secondary-verifier-proxy:
    image: ghcr.io/indicio-tech/proxy-mediator:0.1.1
    environment:
      PORT: 3000
      ENDPOINT: http://secondary-verifier-proxy:3000
      ENABLE_STORE: "true"
      REPO_URI: "${SECONDARY_VERIFIER_PROXY_DB}"
      REPO_KEY: insecure
      LOG_LEVEL: WARNING
    networks:
      - app-network

  secondary-verifier-proxy-setup:
    image: ghcr.io/indicio-tech/proxy-mediator-setup:0.1.1
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=secondary-verifier-proxy:3000,secondary-verifier-agent:3009
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=10
      - PROXY=http://secondary-verifier-proxy:3000
      - AGENT=http://secondary-verifier-agent:8154
      - MEDIATOR_INVITE=https://public.mediator.indiciotech.io?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiMDVlYzM5NDItYTEyOS00YWE3LWEzZDQtYTJmNDgwYzNjZThhIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL3B1YmxpYy5tZWRpYXRvci5pbmRpY2lvdGVjaC5pbyIsICJyZWNpcGllbnRLZXlzIjogWyJDc2dIQVpxSktuWlRmc3h0MmRIR3JjN3U2M3ljeFlEZ25RdEZMeFhpeDIzYiJdLCAibGFiZWwiOiAiSW5kaWNpbyBQdWJsaWMgTWVkaWF0b3IifQ==
    depends_on:
      - secondary-verifier-proxy
      - secondary-verifier-agent
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
